name: Validation du JSON

on:
  pull_request:
    paths:
      - '**/*.json'  # Sâ€™assure que tous les JSON sont pris

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Valider les fichiers JSON
        run: |
          npx ajv-cli validate -s schema.json -d 'scenarios/*.json'
